version: "3"
services:

  productdb:
    image: mysql:5
    networks:
      - devops-spring-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=productdb 
      
  products:
    image: products:7
    ports:
      - "8080:8080"
    networks:
      - devops-spring-mysql
    depends_on:
      - productdb
    command: sh -c "/wait && java -jar products-0.0.1-SNAPSHOT.jar"
    environment:
      - WAIT_HOSTS=productdb:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
 

networks:
  devops-spring-mysql: